// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1E1Vf2XaCfjbdhvwWSE8wXGj8D1k20T0',
    appId: '1:55254149299:web:76f9c1b04f4d01a52c28c6',
    messagingSenderId: '55254149299',
    projectId: 'waves-50603',
    authDomain: 'waves-50603.firebaseapp.com',
    storageBucket: 'waves-50603.appspot.com',
    measurementId: 'G-G0MD0TKL9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgupZ1DC5gSdenqMg5SJrtL9OD8NBLeI',
    appId: '1:55254149299:android:85f6bd56422a02a02c28c6',
    messagingSenderId: '55254149299',
    projectId: 'waves-50603',
    storageBucket: 'waves-50603.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcsFhsrp0GxtDwyEyNUgEkkiGWHKVrdd4',
    appId: '1:55254149299:ios:01c3514b8941614a2c28c6',
    messagingSenderId: '55254149299',
    projectId: 'waves-50603',
    storageBucket: 'waves-50603.appspot.com',
    iosBundleId: 'com.ecency.waves',
  );
}
